services:
    laravel.test:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            mailpit:
                condition: service_healthy
            mysql:
                condition: service_healthy
        restart: unless-stopped
        tty: true
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-finance_tracker}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-db.sql:/docker-entrypoint-initdb.d/01_create-testing-db.sql'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p${DB_PASSWORD:-password}']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - sail
    mailpit:
        image: 'axllent/mailpit:v1.29'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        healthcheck:
            test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8025/api/v1/info']
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
