name: linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure container user
        run: |
          echo "WWWUSER=$(id -u)" >> $GITHUB_ENV
          echo "WWWGROUP=$(id -g)" >> $GITHUB_ENV

      - name: Build PHP 8.5 Container
        run: docker compose build laravel.test

      - name: Install Composer Dependencies
        run: docker compose run --rm --no-deps laravel.test composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: docker compose run --rm --no-deps laravel.test vendor/bin/pint --test
