name: static-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse app database routes tests --level=6 --no-progress --memory-limit=1G --error-format=github
